// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace JqGridCodeGenerator.T4Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class ModelTemplate : ModelTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using AutoMapper;\r\nusing GenericCSR;\r\nusing GenericCSR.Filter;\r\nusing GenericCSR." +
                    "PropertyMapper;\r\nusing PagedList;\r\nusing System;\r\nusing System.Linq.Expressions;" +
                    "\r\n\r\nnamespace ");
            
            #line 19 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseNamespace));
            
            #line default
            #line hidden
            this.Write(".Models\r\n{\r\n\tpublic class ");
            
            #line 21 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\t");
            
            #line 23 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"

			foreach (JqGridCodeGenerator.ViewModel.Column column in columns)
			{
				if(column.IsPrimaryKey)
					continue;
		
            
            #line default
            #line hidden
            this.Write("\t\tpublic ");
            
            #line 29 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Type));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 29 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n\t\t");
            
            #line 30 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"

			}
		
            
            #line default
            #line hidden
            this.Write("\t}\r\n\r\n\tpublic class ");
            
            #line 35 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write("QueryDto : ");
            
            #line 35 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n\t\tpublic ");
            
            #line 37 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeyColumn.Type));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 37 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeyColumn.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n    }\r\n\r\n\tpublic class ");
            
            #line 40 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write("CommandDto : ");
            
            #line 40 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n\t\tpublic int id { get; set; }\r\n    }\r\n\r\n\tpublic class ");
            
            #line 45 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write("ViewModel : GenericJqGridViewModel<");
            
            #line 45 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write("QueryDto> {}\r\n\r\n\tpublic class ");
            
            #line 47 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write("OrderByPredicateCreator : GenericOrderByPredicateCreator<");
            
            #line 47 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 47 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write("PropertyMapper>\r\n\t{\r\n\t\tprotected override Expression<Func<");
            
            #line 49 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write(",dynamic>> GetDefaultOrderByColumn()\r\n\t\t{\r\n\t\t\treturn x=>x.ToDo_DefineDefaultOrder" +
                    "ByColumn;\t\r\n\t\t}\r\n\t}\r\n\r\n\tpublic class ");
            
            #line 55 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write("WherePredicateCreator : GenericWherePredicateCreator<");
            
            #line 55 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 55 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write("PropertyMapper>{}\r\n\r\n\tpublic class ");
            
            #line 57 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write("PropertyMapper : GenericPropertyMapper<");
            
            #line 57 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 57 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write("QueryDto>\r\n\t{\r\n\t\tpublic override Expression<Func<");
            
            #line 59 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write(",dynamic>> GetPathInEfForDtoFieldExpression(string fieldName)\r\n\t\t{\r\n\t\t\t");
            
            #line 61 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"

				foreach (JqGridCodeGenerator.ViewModel.Column column in columns)
				{
			
            
            #line default
            #line hidden
            this.Write("\t\t\tif(fieldName == GetDtoPropertyPathAsString(t=>t.");
            
            #line 65 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write("))\r\n\t\t\t\treturn x => x.");
            
            #line 66 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t");
            
            #line 67 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
						
				}
			
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\tthrow new Exception(\"Putem requesta je poslato nepostojece polje \" + fieldNa" +
                    "me + \r\n\t\t\t\"  Obezbediti da za svako polje iz QueryDto modela postoji odgovarajuc" +
                    "e mapiranje u entity modelu (bazi).\");\r\n\t\t}\r\n\r\n\t}\r\n\r\n\tpublic class ");
            
            #line 77 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write("MappingProfile : Profile\r\n\t{\r\n\t\tpublic ");
            
            #line 79 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write("MappingProfile()\r\n\t\t{\r\n\t\t\tCreateMap<");
            
            #line 81 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 81 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write("QueryDto>();\r\n\r\n\t\t\tCreateMap<");
            
            #line 83 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write("CommandDto,");
            
            #line 83 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write(">()\r\n\t\t\t\t.ForMember(d => d.");
            
            #line 84 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeyColumn.Name));
            
            #line default
            #line hidden
            this.Write(", o => o.MapFrom(s => s.id));\r\n\r\n\t\t\tCreateMap<PagedList<");
            
            #line 86 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write(">, StaticPagedList<");
            
            #line 86 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write("QueryDto>>()\r\n\t\t\t\t.ConvertUsing<PagedListConverter<");
            
            #line 87 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 87 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write("QueryDto>>();\r\n\t\t}\r\n\t}\r\n}");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\ModelTemplate.tt"

private string _baseNameField;

/// <summary>
/// Access the baseName parameter of the template.
/// </summary>
private string baseName
{
    get
    {
        return this._baseNameField;
    }
}

private string _baseNamespaceField;

/// <summary>
/// Access the baseNamespace parameter of the template.
/// </summary>
private string baseNamespace
{
    get
    {
        return this._baseNamespaceField;
    }
}

private string _tableNameField;

/// <summary>
/// Access the tableName parameter of the template.
/// </summary>
private string tableName
{
    get
    {
        return this._tableNameField;
    }
}

private global::JqGridCodeGenerator.ViewModel.Column _primaryKeyColumnField;

/// <summary>
/// Access the primaryKeyColumn parameter of the template.
/// </summary>
private global::JqGridCodeGenerator.ViewModel.Column primaryKeyColumn
{
    get
    {
        return this._primaryKeyColumnField;
    }
}

private global::System.Collections.Generic.List<JqGridCodeGenerator.ViewModel.Column> _columnsField;

/// <summary>
/// Access the columns parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<JqGridCodeGenerator.ViewModel.Column> columns
{
    get
    {
        return this._columnsField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool baseNameValueAcquired = false;
if (this.Session.ContainsKey("baseName"))
{
    this._baseNameField = ((string)(this.Session["baseName"]));
    baseNameValueAcquired = true;
}
if ((baseNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("baseName");
    if ((data != null))
    {
        this._baseNameField = ((string)(data));
    }
}
bool baseNamespaceValueAcquired = false;
if (this.Session.ContainsKey("baseNamespace"))
{
    this._baseNamespaceField = ((string)(this.Session["baseNamespace"]));
    baseNamespaceValueAcquired = true;
}
if ((baseNamespaceValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("baseNamespace");
    if ((data != null))
    {
        this._baseNamespaceField = ((string)(data));
    }
}
bool tableNameValueAcquired = false;
if (this.Session.ContainsKey("tableName"))
{
    this._tableNameField = ((string)(this.Session["tableName"]));
    tableNameValueAcquired = true;
}
if ((tableNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("tableName");
    if ((data != null))
    {
        this._tableNameField = ((string)(data));
    }
}
bool primaryKeyColumnValueAcquired = false;
if (this.Session.ContainsKey("primaryKeyColumn"))
{
    this._primaryKeyColumnField = ((global::JqGridCodeGenerator.ViewModel.Column)(this.Session["primaryKeyColumn"]));
    primaryKeyColumnValueAcquired = true;
}
if ((primaryKeyColumnValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("primaryKeyColumn");
    if ((data != null))
    {
        this._primaryKeyColumnField = ((global::JqGridCodeGenerator.ViewModel.Column)(data));
    }
}
bool columnsValueAcquired = false;
if (this.Session.ContainsKey("columns"))
{
    this._columnsField = ((global::System.Collections.Generic.List<JqGridCodeGenerator.ViewModel.Column>)(this.Session["columns"]));
    columnsValueAcquired = true;
}
if ((columnsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("columns");
    if ((data != null))
    {
        this._columnsField = ((global::System.Collections.Generic.List<JqGridCodeGenerator.ViewModel.Column>)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class ModelTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
