// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace JqGridCodeGenerator.T4Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\RepositoryTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class RepositoryTemplate : RepositoryTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 13 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\RepositoryTemplate.tt"
 if(useBaseRepository) {
	if(baseRepositoryNamespace != baseNamespace+".Repository") 
            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 15 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseRepositoryNamespace));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 16 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\RepositoryTemplate.tt"
 }else{ 
            
            #line default
            #line hidden
            this.Write("using GenericCSR.Repository;\r\n");
            
            #line 18 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\RepositoryTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 19 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseNamespace));
            
            #line default
            #line hidden
            this.Write(".Models;\r\nusing ");
            
            #line 20 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseNamespace));
            
            #line default
            #line hidden
            this.Write(".Repositories.Interfaces;\r\n\r\nnamespace ");
            
            #line 22 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseNamespace));
            
            #line default
            #line hidden
            this.Write(".Repositories\r\n{\r\n\tpublic class ");
            
            #line 24 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write("Repository : \r\n\t");
            
            #line 25 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\RepositoryTemplate.tt"
 if(useBaseRepository) {
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 26 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseRepositoryName));
            
            #line default
            #line hidden
            this.Write("<");
            
            #line 26 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 26 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write("OrderByPredicateCreator,");
            
            #line 26 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write("WherePredicateCreator>,\r\n\t");
            
            #line 27 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\RepositoryTemplate.tt"
 }else{ 
            
            #line default
            #line hidden
            this.Write("\t\tGenericRepository<");
            
            #line 28 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write(",ToDo_ContexType,");
            
            #line 28 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write("OrderByPredicateCreator,");
            
            #line 28 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write("WherePredicateCreator>>,\r\n\t");
            
            #line 29 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\RepositoryTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\tI");
            
            #line 30 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write("Repository\r\n\t{\r\n\t\tprotected override object GetPrimaryKey(");
            
            #line 32 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write(" entity)\r\n\t\t{\r\n\t\t\treturn entity.");
            
            #line 34 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeyName));
            
            #line default
            #line hidden
            this.Write(";\t\t\r\n\t\t}\r\n\t}\r\n}");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Users\DusanRazvoj\Source\Repos\JqGridFileCreatorVsExtension\JqGridCodeGenerator\T4Templates\RepositoryTemplate.tt"

private string _baseNameField;

/// <summary>
/// Access the baseName parameter of the template.
/// </summary>
private string baseName
{
    get
    {
        return this._baseNameField;
    }
}

private string _baseNamespaceField;

/// <summary>
/// Access the baseNamespace parameter of the template.
/// </summary>
private string baseNamespace
{
    get
    {
        return this._baseNamespaceField;
    }
}

private string _tableNameField;

/// <summary>
/// Access the tableName parameter of the template.
/// </summary>
private string tableName
{
    get
    {
        return this._tableNameField;
    }
}

private string _primaryKeyNameField;

/// <summary>
/// Access the primaryKeyName parameter of the template.
/// </summary>
private string primaryKeyName
{
    get
    {
        return this._primaryKeyNameField;
    }
}

private string _baseRepositoryNamespaceField;

/// <summary>
/// Access the baseRepositoryNamespace parameter of the template.
/// </summary>
private string baseRepositoryNamespace
{
    get
    {
        return this._baseRepositoryNamespaceField;
    }
}

private string _baseRepositoryNameField;

/// <summary>
/// Access the baseRepositoryName parameter of the template.
/// </summary>
private string baseRepositoryName
{
    get
    {
        return this._baseRepositoryNameField;
    }
}

private bool _useBaseRepositoryField;

/// <summary>
/// Access the useBaseRepository parameter of the template.
/// </summary>
private bool useBaseRepository
{
    get
    {
        return this._useBaseRepositoryField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool baseNameValueAcquired = false;
if (this.Session.ContainsKey("baseName"))
{
    this._baseNameField = ((string)(this.Session["baseName"]));
    baseNameValueAcquired = true;
}
if ((baseNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("baseName");
    if ((data != null))
    {
        this._baseNameField = ((string)(data));
    }
}
bool baseNamespaceValueAcquired = false;
if (this.Session.ContainsKey("baseNamespace"))
{
    this._baseNamespaceField = ((string)(this.Session["baseNamespace"]));
    baseNamespaceValueAcquired = true;
}
if ((baseNamespaceValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("baseNamespace");
    if ((data != null))
    {
        this._baseNamespaceField = ((string)(data));
    }
}
bool tableNameValueAcquired = false;
if (this.Session.ContainsKey("tableName"))
{
    this._tableNameField = ((string)(this.Session["tableName"]));
    tableNameValueAcquired = true;
}
if ((tableNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("tableName");
    if ((data != null))
    {
        this._tableNameField = ((string)(data));
    }
}
bool primaryKeyNameValueAcquired = false;
if (this.Session.ContainsKey("primaryKeyName"))
{
    this._primaryKeyNameField = ((string)(this.Session["primaryKeyName"]));
    primaryKeyNameValueAcquired = true;
}
if ((primaryKeyNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("primaryKeyName");
    if ((data != null))
    {
        this._primaryKeyNameField = ((string)(data));
    }
}
bool baseRepositoryNamespaceValueAcquired = false;
if (this.Session.ContainsKey("baseRepositoryNamespace"))
{
    this._baseRepositoryNamespaceField = ((string)(this.Session["baseRepositoryNamespace"]));
    baseRepositoryNamespaceValueAcquired = true;
}
if ((baseRepositoryNamespaceValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("baseRepositoryNamespace");
    if ((data != null))
    {
        this._baseRepositoryNamespaceField = ((string)(data));
    }
}
bool baseRepositoryNameValueAcquired = false;
if (this.Session.ContainsKey("baseRepositoryName"))
{
    this._baseRepositoryNameField = ((string)(this.Session["baseRepositoryName"]));
    baseRepositoryNameValueAcquired = true;
}
if ((baseRepositoryNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("baseRepositoryName");
    if ((data != null))
    {
        this._baseRepositoryNameField = ((string)(data));
    }
}
bool useBaseRepositoryValueAcquired = false;
if (this.Session.ContainsKey("useBaseRepository"))
{
    this._useBaseRepositoryField = ((bool)(this.Session["useBaseRepository"]));
    useBaseRepositoryValueAcquired = true;
}
if ((useBaseRepositoryValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("useBaseRepository");
    if ((data != null))
    {
        this._useBaseRepositoryField = ((bool)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class RepositoryTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
